# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddQuestiontest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addQuestiontest(self):
    # Test name: AddQuestion_test
    # Step # | name | target | value
    # 1 | open | http://localhost:3000/TeacherHome | 
    self.driver.get("http://localhost:3000/TeacherHome")
    # 2 | setWindowSize | 1050x700 | 
    self.driver.set_window_size(1050, 700)
    # 3 | click | linkText=Add Question | 
    self.driver.find_element(By.LINK_TEXT, "Add Question").click()
    # 4 | click | css=.bg-white:nth-child(4) .bg-blue-500 | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(4) .bg-blue-500").click()
    # 5 | click | css=.block:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(1)").click()
    # 6 | type | css=.block:nth-child(1) | b
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(1)").send_keys("b")
    # 7 | click | css=.block:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(2)").click()
    # 8 | type | css=.block:nth-child(2) | b
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(2)").send_keys("b")
    # 9 | click | css=.block:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(3)").click()
    # 10 | type | css=.block:nth-child(3) | b
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(3)").send_keys("b")
    # 11 | click | css=.block:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(4)").click()
    # 12 | type | css=.block:nth-child(4) | bb
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(4)").send_keys("bb")
    # 13 | click | css=.block:nth-child(5) | 
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(5)").click()
    # 14 | type | css=.block:nth-child(5) | b
    self.driver.find_element(By.CSS_SELECTOR, ".block:nth-child(5)").send_keys("b")
    # 15 | click | css=.bg-blue-500:nth-child(7) | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500:nth-child(7)").click()
    # 16 | assertAlert | Question added successfully | 
    assert self.driver.switch_to.alert.text == "Question added successfully"
  
