# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreateQuiztest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createQuiztest(self):
    # Test name: CreateQuiz_test
    # Step # | name | target | value
    # 1 | open | http://localhost:3000/TeacherHome | 
    self.driver.get("http://localhost:3000/TeacherHome")
    # 2 | setWindowSize | 1050x700 | 
    self.driver.set_window_size(1050, 700)
    # 3 | click | linkText=Create Quiz | 
    self.driver.find_element(By.LINK_TEXT, "Create Quiz").click()
    # 4 | click | css=.mb-6:nth-child(1) > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-6:nth-child(1) > .w-full").click()
    # 5 | type | css=.mb-6:nth-child(1) > .w-full | a
    self.driver.find_element(By.CSS_SELECTOR, ".mb-6:nth-child(1) > .w-full").send_keys("a")
    # 6 | click | css=.mb-6:nth-child(2) > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-6:nth-child(2) > .w-full").click()
    # 7 | type | css=.mb-6:nth-child(2) > .w-full | a
    self.driver.find_element(By.CSS_SELECTOR, ".mb-6:nth-child(2) > .w-full").send_keys("a")
    # 8 | click | css=.bg-gray-50 > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-50 > .w-full").click()
    # 9 | type | css=.bg-gray-50 > .w-full | a
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-50 > .w-full").send_keys("a")
    # 10 | click | css=.mt-2:nth-child(3) > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(3) > .w-full").click()
    # 11 | type | css=.mt-2:nth-child(3) > .w-full | a
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(3) > .w-full").send_keys("a")
    # 12 | click | css=.mt-2:nth-child(4) > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(4) > .w-full").click()
    # 13 | type | css=.mt-2:nth-child(4) > .w-full | a
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(4) > .w-full").send_keys("a")
    # 14 | click | css=.mt-2:nth-child(5) > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(5) > .w-full").click()
    # 15 | type | css=.mt-2:nth-child(5) > .w-full | a
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(5) > .w-full").send_keys("a")
    # 16 | click | css=.mt-2:nth-child(6) > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(6) > .w-full").click()
    # 17 | type | css=.mt-2:nth-child(6) > .w-full | a
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(6) > .w-full").send_keys("a")
    # 18 | click | css=.mt-2:nth-child(7) > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(7) > .w-full").click()
    # 19 | select | css=.mt-2:nth-child(7) > .w-full | label=Option 1
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".mt-2:nth-child(7) > .w-full")
    dropdown.find_element(By.XPATH, "//option[. = 'Option 1']").click()
    # 20 | click | css=.w-full:nth-child(5) | 
    self.driver.find_element(By.CSS_SELECTOR, ".w-full:nth-child(5)").click()
  
